name: Build Mobile App
description: A composite action to build an expo app.

inputs:
  expo-token:
    description: 'Expo token'
    required: true
  platform:
    description: 'Platform to build for (all/android/ios)'
    required: true
  profile:
    description: 'EAS build profile (preview/development/production)'
    required: true
  submit:
    description: 'Auto submit to the store? (production only)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.13.2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Install modules
      shell: bash
      run: pnpm i

    - name: Build app
      shell: bash
      run: pnpm run build

    - name: Prebuild expo app
      shell: bash
      working-directory: apps/mobile
      run: npx expo prebuild

    - name: Send build to eas
      shell: bash
      if: ${{ !inputs.submit || inputs.profile != 'production' }}
      working-directory: apps/mobile
      run: eas build --non-interactive --wait --platform=${{ inputs.platform }} --profile=${{ inputs.profile }}

    - name: Build & submit mobile
      shell: bash
      if: ${{ inputs.submit && inputs.profile == 'production' }}
      working-directory: apps/mobile
      run: eas build --non-interactive --wait --auto-submit --platform=${{ inputs.platform }} --profile=${{ inputs.profile }}
