name: Run WebdriverIO tests
description: A composite action to run WebdriverIO tests

runs:
  using: 'composite'
  steps:

  - name: Install Chromium
    shell: bash
    run: sudo apt-get install -y chromium-browser

  - name: Install pnpm
    uses: pnpm/action-setup@v4
    with:
      version: 10.15.0

  - name: Install Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: 'pnpm'

  - name: Install modules
    shell: bash
    run: pnpm i

  - name: Install test modules
    shell: bash
    run: pnpm -C tests-e2e install --frozen-lockfile

  - name: Build app
    shell: bash
    run: pnpm run build-e2e
    env:
      SPRINGBOARD_PLATFORM_VARIANT: main

  - name: Run tests
    shell: bash
    run: pnpm -C tests-e2e test
    env:
      CI: true

  - name: Upload screenshots
    if: failure()
    uses: actions/upload-artifact@v4
    with:
      name: screenshots
      path: tests-e2e/screenshots
