name: build_mobile

on:
  # push:
  #   branches:
  #   - '*'

  repository_dispatch:
    types: [ build-remote, new-commit-on-main, build-for-pr ]

  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
        - all
        - android
        - ios
      profile:
        description: EAS build profile (preview/development/production)
        type: choice
        required: true
        default: preview
        options:
        - preview
        - development
        - production
      run_on_eas:
        description: Run build on eas? Will run locally in CI if false
        type: boolean
        default: false
      submit:
        description: Auto submit to the store? (production only)
        type: boolean
        required: false
      output_eas_build_to_logs:
        description: Output EAS build to logs (if false, sends to /dev/null)
        type: boolean
        required: false
        default: false
      ref:
        description: 'Ref to use in application repo'
        required: false
        default: 'main'

env:
  TARGET_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref || github.event_name == 'repository_dispatch' && github.event.client_payload.sha != '' && github.event.client_payload.sha || 'main' }}

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
    - name: Log Workflow Inputs
      run: |
        echo "Event: ${{ github.event_name }} - ${{ github.event.action }}"
        echo "platform: ${{ github.event.inputs.platform || github.event.client_payload.platform }}"
        echo "profile: ${{ github.event.inputs.profile || github.event.client_payload.profile }}"
        echo "run_on_eas: ${{ github.event.inputs.run_on_eas || github.event.client_payload.run_on_eas }}"
        echo "submit: ${{ github.event.inputs.submit || github.event.client_payload.submit }}"
        echo "output_eas_build_to_logs: ${{ github.event.inputs.output_eas_build_to_logs || github.event.client_payload.output_eas_build_to_logs }}"
        echo "ref: ${{ github.event.inputs.ref || github.event.client_payload.sha }}"
        echo "TARGET_BRANCH: ${{ env.TARGET_BRANCH }}"
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "Repository: ${{ github.event.client_payload.repository }}"
          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
          echo "Run ID: ${{ github.event.client_payload.run_id }}"
        fi
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.REPO_TOKEN }}
        ref: ${{ env.TARGET_BRANCH }}

    - name: Checkout releases repo into `.github/composite-actions`
      uses: actions/checkout@v3
      with:
        repository: jamtools/releases
        path: .github/composite-actions
        ref: ${{ github.sha }}

    - name: Build Mobile App with EAS
      # if: ${{ github.event.action != 'new-commit-on-main' }}
      uses: ./.github/composite-actions/.github/actions/build_mobile_eas
      with:
        local: ${{ (github.event.action == 'build-for-pr' && !github.event.client_payload.run_on_eas) || (github.event.action != 'build-for-pr' && !inputs.run_on_eas) }}
        platform: ${{ inputs.platform || (github.event.action == 'build-for-pr' && github.event.client_payload.platform) || 'android' }}
        profile: ${{ inputs.profile || (github.event.action == 'build-for-pr' && github.event.client_payload.profile) || 'production' }}
        submit: ${{ inputs.submit }}
        output_logs: ${{ inputs.output_eas_build_to_logs || github.event.client_payload.output_eas_build_to_logs || false }}
        expo-token: ${{ secrets.EXPO_TOKEN }}
        asc_app_id: ${{ secrets.ASC_APP_ID }}
        discord_webhook_url: ${{ secrets.DISCORD_APP_BUILDS_WEBHOOK_URL }}

    # - name: Build Mobile App and Submit with EAS
    #   if: ${{ github.event.action == 'new-commit-on-main' }}
    #   uses: ./.github/composite-actions/.github/actions/build_mobile_eas
    #   with:
    #     local: false
    #     platform: 'all'
    #     profile: 'production'
    #     submit: false
    #     output_logs: false
    #     expo-token: ${{ secrets.EXPO_TOKEN }}
    #     asc_app_id: ${{ secrets.ASC_APP_ID }}
    #     discord_webhook_url: ${{ secrets.DISCORD_APP_BUILDS_WEBHOOK_URL }}

    # - name: Build Mobile App with Gradle
    #   uses: ./.github/composite-actions/.github/actions/build_mobile_gradle
    #   with:
    #     build-type: debug
