name: Desktop Build Default Platform

on:
  push:
    branches:
    - '*'

  repository_dispatch:
    types: [ build-remote ]

  workflow_dispatch:
    inputs:
      host_platform:
        description: Platform to build for (macos/all)
        type: choice
        required: true
        default: macos
        options:
        - macos
        - all
      sign_app:
        description: 'Sign app'
        required: true
        type: boolean
        default: true
      # profile:
      #   description: Build profile (preview/development/production)
      #   type: choice
      #   required: true
      #   default: preview
      #   options:
      #   - preview
      #   - development
      #   - production
      # submit:
      #   description: Auto submit to the store? (production only)
      #   type: boolean
      #   required: false
      ref:
        description: 'Ref to use in application repo'
        required: false
        default: 'main'

env:
  TARGET_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref || github.event_name == 'repository_dispatch' && github.event.client_payload.sha != '' && github.event.client_payload.sha || 'main' }}

jobs:
  build_desktop_mac:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            tauri_target: 'aarch64-apple-darwin'
            # pkg_target: 'node20-macos-arm64'
          # - platform: 'macos-latest'
          #   args: '--target x86_64-apple-darwin'
          #   tauri_target: 'x86_64-apple-darwin'
          #   pkg_target: 'node20-macos-x64'
          # - platform: 'ubuntu-22.04'
          #   args: ''
          #   tauri_target: ''
          #   pkg_target: 'node20-linux-x64'
          # - platform: 'windows-latest'
          #   args: ''
          #   tauri_target: ''
          #   pkg_target: 'node20-windows-x64'

    uses: ./.github/workflows/build_desktop_common.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      tauri_args: ${{ matrix.args }}
      tauri_target: ${{ matrix.tauri_target }}
      # pkg_target: ${{ matrix.pkg_target }}
      sign_app: ${{ github.event.inputs.sign_app || false }}
      target_branch: desktop-online
      # target_branch: ${{ env.TARGET_BRANCH }}
