name: Desktop Build Default Platform

on:
  # push:
  #   branches:
  #   - '*'

  repository_dispatch:
    types: [ build-remote ]

  workflow_dispatch:
    inputs:
      sign_app:
        description: 'Sign app'
        required: true
        type: boolean
        default: true
      profile:
        description: Build profile (development/preview/production)
        type: choice
        required: true
        default: development
        options:
        - preview
        - development
        - production
      custom_profile:
        description: 'Custom build profile'
        type: string
        required: false
      ref:
        description: 'Ref to use in application repo'
        required: false
        default: 'main'
      site_url:
        description: 'Site URL'
        required: true
      run_on_self_hosted:
        description: 'Run on self-hosted runner'
        required: true
        type: boolean
        default: false
      publish_version:
        description: 'Publish version'
        required: false
        type: string
      enable_debug:
        description: 'Enable debug'
        required: false
        type: boolean
        default: false

env:
  TARGET_BRANCH: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref) || (github.event_name == 'repository_dispatch' && github.event.client_payload.sha != '' && github.event.client_payload.sha) || 'main' }}

jobs:
  set_status_pending:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:
    - name: Set commit status to pending
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: '${{ secrets.REPO }}'.split('/')[0],
            repo: '${{ secrets.REPO }}'.split('/')[1],
            sha: '${{ env.TARGET_BRANCH }}',
            state: 'pending',
            context: 'Desktop Build Default Platform / build_desktop_mac',
            description: 'Desktop build in progress...'
          });
  build_desktop_mac:
    needs: [set_status_pending]
    if: always()
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
            tauri_target: 'universal-apple-darwin'
            # tauri_target: 'aarch64-apple-darwin'
            # pkg_target: 'node20-macos-arm64'
          # - platform: 'macos-latest'
          #   args: '--target x86_64-apple-darwin'
          #   tauri_target: 'x86_64-apple-darwin'
          #   # pkg_target: 'node20-macos-x64'
          # - platform: 'ubuntu-22.04'
          #   args: ''
          #   tauri_target: ''
          #   # pkg_target: 'node20-linux-x64'
          # - platform: 'windows-latest'
          #   args: ''
          #   tauri_target: ''
          #   # pkg_target: 'node20-windows-x64'

    uses: ./.github/workflows/build_desktop_common.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      tauri_args: ${{ matrix.args }}
      tauri_target: ${{ matrix.tauri_target }}
      # pkg_target: ${{ matrix.pkg_target }}
      sign_app: ${{ github.event.inputs.sign_app == 'true' }}
      target_branch: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref) || (github.event_name == 'repository_dispatch' && github.event.client_payload.sha != '' && github.event.client_payload.sha) || 'main' }}
      profile: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.custom_profile || github.event.inputs.profile)) || (github.event_name == 'repository_dispatch' && github.event.client_payload.profile) }}
      site_url: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.site_url) || (github.event_name == 'repository_dispatch' && github.event.client_payload.site_url) }}
      run_on_self_hosted: ${{ github.event.inputs.run_on_self_hosted == 'true' }}
      publish_version: ${{ github.event.inputs.publish_version }}
      enable_debug: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.enable_debug == 'true') }}
  set_status_complete:
    runs-on: ubuntu-latest
    needs: [build_desktop_mac]
    if: github.event_name == 'repository_dispatch' && always()
    steps:
    - name: Set commit status to success
      if: needs.build_desktop_mac.result == 'success'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: '${{ secrets.REPO }}'.split('/')[0],
            repo: '${{ secrets.REPO }}'.split('/')[1],
            sha: '${{ env.TARGET_BRANCH }}',
            state: 'success',
            context: 'Desktop Build Default Platform / build_desktop_mac',
            description: 'Desktop build completed successfully'
          });
    - name: Set commit status to failure
      if: needs.build_desktop_mac.result != 'success'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: '${{ secrets.REPO }}'.split('/')[0],
            repo: '${{ secrets.REPO }}'.split('/')[1],
            sha: '${{ env.TARGET_BRANCH }}',
            state: 'failure',
            context: 'Desktop Build Default Platform / build_desktop_mac',
            description: 'Desktop build failed'
          });
