name: build_mobile

on:
  push:
    branches:
      - '*'

  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
          - all
          - android
          - ios
      profile:
        description: EAS build profile (preview/development/production)
        type: choice
        required: true
        default: preview
        options:
          - preview
          - development
          - production
      submit:
        description: Auto submit to the store? (production only)
        type: boolean
        required: false

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout songdrive-releases repo into `.github/composite-actions`
        uses: actions/checkout@v3
        with:
          repository: jamtools/songdrive-releases
          path: .github/composite-actions
          ref: ${{ github.sha }}

      # - name: Build and Test
      #   uses: ./.github/composite-actions/.github./actions/build_mobile_composite_action

      - name: List directories recursively
        run: ls -alR
