name: update_mobile

on:
  # push:
  #   branches:
  #   - '*'

  repository_dispatch:
    types: [ new-commit-on-main ]

  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
        - all
        - android
        - ios
      profile:
        description: EAS build profile (preview/development/production)
        type: choice
        required: true
        default: preview
        options:
        - preview
        - development
        - production
      ref:
        description: 'Ref to use in application repo (ignored for now)'
        required: false
        default: 'main'
      message:
        description: Update message (e.g., "Bug fixes and improvements")
        type: string
        required: true
      site_url:
        description: 'Site URL'
        required: true

env:
  TARGET_BRANCH: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref) || (github.event_name == 'repository_dispatch' && github.event.client_payload.sha != '' && github.event.client_payload.sha) || 'main' }}
  SITE_URL: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.site_url) || (github.event_name == 'repository_dispatch' && github.event.client_payload.site_url) }}
  PROFILE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.profile) || (github.event_name == 'repository_dispatch' && github.event.client_payload.profile) }}

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
    - name: Log Workflow Inputs
      run: |
        echo "platform: ${{ github.event.inputs.platform }}"
        echo "profile: ${{ env.PROFILE }}"
        echo "ref: ${{ github.event.inputs.ref }}"
        echo "TARGET_BRANCH: ${{ env.TARGET_BRANCH }}"
        echo "SITE_URL: ${{ env.SITE_URL }}"
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.REPO_TOKEN }}
        ref: ${{ env.TARGET_BRANCH }}

    - name: Checkout songdrive-releases repo into `.github/composite-actions`
      uses: actions/checkout@v3
      with:
        repository: jamtools/songdrive-releases
        path: .github/composite-actions
        ref: ${{ github.sha }}

    - name: Update Mobile App with EAS
      uses: ./.github/composite-actions/.github/actions/update_mobile_eas
      with:
        platform: ${{ inputs.platform || 'all' }}
        profile: ${{ env.PROFILE }}
        expo-token: ${{ secrets.EXPO_TOKEN }}
        site_url: ${{ env.SITE_URL }}
